/**
 * Pre-bakes "What's nearby" data for all properties with coords.
 * Run once: node scripts/prebake-nearby.mjs
 * Output: src/data/nearby-data.js
 *
 * IMPORTANT: API key must have no HTTP referrer restrictions to run from local machine.
 * Temporarily remove them in Google Cloud Console → Credentials, run this, then restore.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT  = join(__dir, '..')

const KEY = (() => {
  const env = readFileSync(join(ROOT, '.env.local'), 'utf8')
  const m = env.match(/GOOGLE_PLACES_API_KEY=(.+)/)
  return m ? m[1].trim() : null
})()
if (!KEY) { console.error('No GOOGLE_PLACES_API_KEY in .env.local'); process.exit(1) }

const TYPES  = ['restaurant', 'bar', 'night_club', 'hospital', 'pharmacy', 'atm', 'bank', 'park', 'natural_feature']
const RADIUS = 2000
const CHECKPOINT = join(__dir, '.nearby-checkpoint.json')

let checkpoint = {}
if (existsSync(CHECKPOINT)) {
  checkpoint = JSON.parse(readFileSync(CHECKPOINT, 'utf8'))
  console.log(`Resuming — ${Object.keys(checkpoint).length} locations already done`)
}

// Parse id + coords pairs from a JS file using line-by-line scanning
function extractCoords(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n')
  const out = []
  let currentId = null
  for (const line of lines) {
    const idMatch = line.match(/^\s+id:\s*(\d+|'[^']+'|"[^"]+")/)
    if (idMatch) {
      const raw = idMatch[1]
      currentId = raw.startsWith("'") || raw.startsWith('"') ? raw.slice(1, -1) : Number(raw)
    }
    const coordMatch = line.match(/coords:\s*\{\s*lat:\s*([\d.-]+),\s*lng:\s*([\d.-]+)/)
    if (coordMatch && currentId !== null) {
      out.push({ id: currentId, lat: parseFloat(coordMatch[1]), lng: parseFloat(coordMatch[2]) })
      currentId = null
    }
  }
  return out
}

const coreProps   = extractCoords(join(ROOT, 'src/data/properties.js'))
const googleProps = extractCoords(join(ROOT, 'src/data/google-properties.js'))

// Dedupe by id
const seen = new Set()
const props = [...coreProps, ...googleProps].filter(p => seen.has(p.id) ? false : seen.add(p.id))
console.log(`Total locations with coords: ${props.length}`)

async function fetchType(lat, lng, type) {
  const url = `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=${lat},${lng}&radius=${RADIUS}&type=${type}&key=${KEY}`
  const r = await fetch(url)
  const d = await r.json()
  if (d.status === 'REQUEST_DENIED') {
    console.error('\nAPI key denied:', d.error_message)
    console.error('→ Remove HTTP referrer restrictions from the key in Google Cloud Console, then retry.')
    process.exit(1)
  }
  return (d.results || []).slice(0, 5).map(p => ({
    name: p.name,
    rating: p.rating || null,
    vicinity: p.vicinity || null,
    place_id: p.place_id,
  }))
}

async function fetchLocation(id, lat, lng) {
  const results = []
  for (const type of TYPES) {
    try {
      const places = await fetchType(lat, lng, type)
      results.push({ type, places })
    } catch {
      results.push({ type, places: [] })
    }
    await new Promise(r => setTimeout(r, 150))
  }
  return results
}

let done = Object.keys(checkpoint).length
for (const { id, lat, lng } of props) {
  const key = String(id)
  if (checkpoint[key]) { continue }

  process.stdout.write(`[${done + 1}/${props.length}] ${id} (${lat},${lng}) ... `)
  const results = await fetchLocation(id, lat, lng)
  checkpoint[key] = { id, results }
  writeFileSync(CHECKPOINT, JSON.stringify(checkpoint))
  done++
  console.log('✓')
}

// Group results into categories
function groupResults(results) {
  const CATS = {
    restaurant: ['restaurant'],
    nightlife:  ['bar', 'night_club'],
    medical:    ['hospital', 'pharmacy'],
    atm:        ['atm', 'bank'],
    nature:     ['park', 'natural_feature'],
  }
  const out = Object.fromEntries(Object.keys(CATS).map(k => [k, []]))
  for (const { type, places } of results) {
    for (const [cat, types] of Object.entries(CATS)) {
      if (types.includes(type)) { out[cat].push(...places); break }
    }
  }
  for (const cat of Object.keys(out)) {
    const seen = new Set()
    out[cat] = out[cat].filter(p => seen.has(p.name) ? false : seen.add(p.name))
  }
  return out
}

const finalMap = {}
for (const [id, entry] of Object.entries(checkpoint)) {
  finalMap[id] = groupResults(entry.results)
}

const outPath = join(ROOT, 'src/data/nearby-data.js')
writeFileSync(outPath, `// Auto-generated by scripts/prebake-nearby.mjs — do not edit manually\nexport const nearbyData = ${JSON.stringify(finalMap)}\n`)
console.log(`\nWrote ${Object.keys(finalMap).length} entries → src/data/nearby-data.js`)
