import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT  = join(__dir, '..')

const KEY = (() => {
  const env = readFileSync(join(ROOT, '.env.local'), 'utf8')
  const m = env.match(/GOOGLE_PLACES_API_KEY=(.+)/)
  return m ? m[1].trim() : null
})()

const TYPES = ['restaurant','bar','night_club','hospital','pharmacy','atm','bank','park','natural_feature']
const CATS  = {
  restaurant: ['restaurant'], nightlife: ['bar','night_club'],
  medical: ['hospital','pharmacy'], atm: ['atm','bank'], nature: ['park','natural_feature'],
}

const [,, id, lat, lng] = process.argv
if (!id || !lat || !lng) { console.error('Usage: node refetch-one.mjs <id> <lat> <lng>'); process.exit(1) }

const raw = []
for (const type of TYPES) {
  const url = `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=${lat},${lng}&radius=2000&type=${type}&key=${KEY}`
  const d = await fetch(url).then(r => r.json())
  const places = (d.results || []).slice(0, 5).map(p => ({ name: p.name, rating: p.rating || null, vicinity: p.vicinity || null, place_id: p.place_id }))
  raw.push({ type, places })
  console.log(`${type}: ${places.length} results`)
  await new Promise(r => setTimeout(r, 150))
}

const grouped = Object.fromEntries(Object.keys(CATS).map(k => [k, []]))
for (const { type, places } of raw) {
  for (const [cat, types] of Object.entries(CATS)) {
    if (types.includes(type)) { grouped[cat].push(...places); break }
  }
}
for (const cat of Object.keys(grouped)) {
  const seen = new Set()
  grouped[cat] = grouped[cat].filter(p => seen.has(p.name) ? false : seen.add(p.name))
}

// Patch nearby-data.js
const dataPath = join(ROOT, 'src/data/nearby-data.js')
const src = readFileSync(dataPath, 'utf8')
  .replace(/^\/\/[^\n]*\n/, '')           // strip comment line
  .replace('export const nearbyData =', '')
  .trim().replace(/;?\s*$/, '')
const data = JSON.parse(src)
data[id] = grouped
writeFileSync(dataPath, `// Auto-generated by scripts/prebake-nearby.mjs — do not edit manually\nexport const nearbyData = ${JSON.stringify(data)}\n`)
console.log(`\nPatched property ${id}:`, Object.entries(grouped).map(([k,v]) => `${k}:${v.length}`).join(' '))
